version: '3.8'

services:
  backend:
    build: 
      context: ./Rainmaker-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TIDB_URL=${TIDB_URL}
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SONAR_API_KEY=${SONAR_API_KEY}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - CLEARBIT_API_KEY=${CLEARBIT_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=true
    depends_on:
      - redis
    volumes:
      - ./Rainmaker-backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./Rainmaker-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./Rainmaker-frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build:
      context: ./Rainmaker-backend
      dockerfile: Dockerfile
    environment:
      - TIDB_URL=${TIDB_URL}
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SONAR_API_KEY=${SONAR_API_KEY}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - CLEARBIT_API_KEY=${CLEARBIT_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - redis
    volumes:
      - ./Rainmaker-backend:/app
    command: celery -A app.workers.celery_app worker --loglevel=info

volumes:
  redis_data: